# Generated by Django 4.1.1 on 2022-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.ManyToManyField(blank=True, to='accounts.address', verbose_name='آدرس(ها)'),
        ),
    ]
