# Generated by Django 4.1.1 on 2022-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_branches',
            field=models.ManyToManyField(blank=True, related_name='product_other_branch', to='shop.productoptions'),
        ),
    ]
