# Generated by Django 4.1.1 on 2022-10-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_productoptions_options_productoptions__type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='_type',
            field=models.CharField(blank=True, choices=[('normal', 'NORMAL'), ('edit', 'EDIT'), ('full_edit', 'FULL_EDIT')], max_length=10, null=True),
        ),
    ]
