# Generated by Django 4.1.1 on 2022-10-04 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productoptions_user_alter_productoptions__type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selected_product',
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_selected_product', to='shop.productoptions'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='op_design',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام طرح'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='op_image',
            field=models.ImageField(upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='عکس طرح'),
        ),
    ]
