# Generated by Django 4.1.1 on 2022-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_selected_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order',
            new_name='orders',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
