# Generated by Django 4.1.1 on 2022-10-06 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_order_orderitems_orders_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='is_on_debt',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده'),
        ),
    ]
