# Generated by Django 4.1.1 on 2022-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_coupon_orderitems_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='created_card',
            field=models.BooleanField(default=False),
        ),
    ]
