# Generated by Django 4.1.1 on 2022-10-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='scan_option',
            field=models.CharField(choices=[('nfc', 'NFC'), ('nfc+qrcode', 'NFC & QRcode')], default='nfc', max_length=11),
        ),
    ]
