# Generated by Django 4.1.1 on 2022-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productoptions_scan_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptions',
            name='scan_option',
        ),
        migrations.AddField(
            model_name='cart',
            name='scan_option',
            field=models.CharField(choices=[('nfc', 'NFC'), ('nfc+qrcode', 'NFC & QRcode')], default='nfc', max_length=11),
        ),
    ]
