# Generated by Django 4.1.1 on 2022-11-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cart_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_type',
            field=models.CharField(blank=True, choices=[('normal', 'NORMAL'), ('edit', 'EDIT'), ('full_edit', 'FULL_EDIT')], max_length=10, null=True),
        ),
    ]
