# Generated by Django 4.1.1 on 2022-11-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_type',
            new_name='typeof',
        ),
    ]
