# Generated by Django 4.1.1 on 2022-11-20 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename__type_product_typeof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptions',
            old_name='_type',
            new_name='typeof',
        ),
        migrations.AddField(
            model_name='cart',
            name='card_design',
            field=models.ImageField(blank=True, null=True, upload_to='card_photo_desing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='عکس طرح'),
        ),
        migrations.AddField(
            model_name='cart',
            name='card_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
