# Generated by Django 4.1.1 on 2022-11-07 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_userinfo_selected_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='page_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pages/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='bannerandimage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='bannerandimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='banners/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='cryptowalletaddress',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='faq',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='freetext',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='links',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='navigations',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
    ]
