# Generated by Django 4.1.1 on 2022-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_bankaccounts_icon_alter_bannerandimage_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='page_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
